version: '3'

services:
    app:
        build: .
        container_name: web
        ports:
            - '${WEB_PORT:-0}:80'
        volumes:
            - ./:/var/www/html
    db:
        image: mysql:8
        restart: always
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
        ports:
            - '3306:3306'
